- name: Variables in a play level
  hosts: localhost
  vars:
    COURSE: "DEVOPS"
    NAME: 'APARNA'
  tasks:
  - name: printing the Play Variables
    ansible.builtin.debug:
      msg: "My name is {{NAME}} and i am learning {{COURSE}}"